[package]
name = "core"
version = "0.2.0"
edition = "2021"

[dependencies]
image = "0.25.4"
webp = "0.3.0"
# rand = "0.8.5"
rand = { version = "0.8", features = ["small_rng"] }

serde_json = "1.0.132"
# image_compressor = "1.5.2"
base64 = "0.22.1"
flate2 = "1.0"
rayon = "1.5"