name: Setup Database

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-db:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: > 
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Wait for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB...";
            sleep 3;
          done
      - name: Save MongoDB configuration
        run: echo "MONGO_URL=mongodb://root:example@localhost:27017" >> $GITHUB_ENV
